### ISSUE TITLE
Screenshots for the desktop client FAQs

### ISSUE THREAD

**Issue by gabi18** [owncloud/docs-client-desktop#128]
Related pull request: https://github.com/owncloud/docs-client-desktop/pull/123

This issue is about providing screenshots to replace files in .../docs-client-desktop/modules/ROOT/assets/images/faq.

(1) multiple-accounts-sharing-folder.png

![Multiple_accounts](https://user-images.githubusercontent.com/75983861/137882250-d05d4519-cc65-4537-a571-6c08c2bec83d.png)

(2) folder-used-in-sync-connection1.png

![already_used_sync](https://user-images.githubusercontent.com/75983861/138060281-fefd029e-42e3-4eee-8b0b-1cf44fba0399.png)

(3) folder-used-in-sync-connection2.png

![already_used_sync2](https://user-images.githubusercontent.com/75983861/138064676-2d194b38-8715-44b2-96b5-cf13e69a1646.png)

(4) folder-used-by-different-client.png

![used_OneDrive](https://user-images.githubusercontent.com/75983861/138067465-87aac807-ea28-4427-982a-65d247939fbe.png)

(5) folder-managed-by-another-sync-client.png

![managed_by_subfolder](https://user-images.githubusercontent.com/75983861/138107931-08feeba5-c491-4cf7-a1d0-ed71bb301eb3.png)

**Comment by mmattel** [comment]
Closing via #123
