### ISSUE TITLE
[QA] WinVFS with Win Storage Sense

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs-client-desktop#129]
- https://support.microsoft.com/en-us/office/use-onedrive-and-storage-%3Cmark%3Esense%3C/mark%3E-in-windows-10-to-manage-disk-space-de5faa9a-6108-4be1-87a6-d90688d08a48
  - https://www.tenforums.com/tutorials/112382-automatically-make-onedrive-files-demand-online-only-windows-10-a.html

**Comment by mmattel** [comment]
During my investigations, I came across following point. If you see the image below, the OneDrive folder name contains the users SID. But when looking to the owncloud folder, the name has an "encrypted" string which I guess is related to a owncloud connection and differs if you have more vfs connections set.

![image](https://user-images.githubusercontent.com/3321281/149371404-5693fb88-9086-4dfd-af71-f5b66ed9d1ea.png)

Looking into the settings via the GUI, the connection is clearly stated and can be differenciated. Without having it tried, my guess is that there is for each connection a seperate entry.

![image](https://user-images.githubusercontent.com/3321281/149373332-a8963f01-2180-4794-966e-dcfba498c672.png)

**My question is**, how can an admin distinguish by the folder in regedit which connection is addressed.

**Comment by mmattel** [comment]
Ping...
Did not hear anything till now, can continue to work on when infos provided.

@michl19 fyi

**Comment by TheOneRing** [comment]
We don't support managing storage sense using regedit

**Comment by michaelstingl** [comment]
superseded by https://github.com/owncloud/docs-client-desktop/issues/124
