### ISSUE TITLE
[Linux AppImage] Document installation and use of AppImages

### ISSUE THREAD

**Issue by gabi18** [owncloud/docs-client-desktop#206]
__General__
 
AppImage is a different way to install Linux applications - not several files (packages) in several places but one file (ending .AppImage) containing the application and all necessary dependency and libraries. There is only a single application AppImage which runs on all (modern) Linux platforms.

There are known issues for these platforms with the 2.10.1 AppImage:
- doesn't run on CentOS 7 -> https://github.com/owncloud/client/issues/9195
- issue with libfuse on Ubuntu 22.04 -> https://docs.appimage.org/user-guide/troubleshooting/fuse.html

How To Use AppImages in Linux
-> https://docs.appimage.org/user-guide (official appimage doc)
-> https://itsfoss.com/use-appimage-linux/

__Install and run an AppImage__

-> https://docs.appimage.org/introduction/quickstart.html#ref-quickstart
- download xyz.AppImage from https://owncloud.com/desktop-app/ _Linux_ (and move it to $HOME/Applications or $HOME/bin)
- make it executable in file browser or on command line (```chmod +x xyz.AppImage```)
- run the AppImage by double click or on command line  with ```./xyz.AppImage -s``` (start on command line with '-s' option: the client settings window is shown)
- to remove the AppImage from your system simply delete the xyz.AppImage file.

Note: to see systray client icons on Debian 11 ```apt install gnome-shell-extension-appindicator``` and enable 'Ubuntu appindicators' in "Tweaks/Extensions" 

__System integration__

Install AppImageLauncher -> https://docs.appimage.org/user-guide/run-appimages.html#appimagelauncher
 - download the appropriate package, see https://github.com/TheAssassin/AppImageLauncher/#system-wide-installation from https://github.com/TheAssassin/AppImageLauncher/releases/
 - install with a graphical install tool (right click and choose the installer); if not possible see https://github.com/TheAssassin/AppImageLauncher/wiki/Install-on-Ubuntu-or-Debian
 - double click on xyz.AppImage (downloaded to $HOME/Downloads) to start the AppImageLauncher and let it do the integration
 - starting the client is possible now from ```Show Applications``` resp. ```Application Launcher``` 
 - removing the AppImage is also possible here on right click
  
Note: the 'rpm' package isn't signed (yet). Install e.g. on openSUSE using ```zypper install appimagelauncher-xxx.rpm``` and ignore that signature verification failed.

__Limitations__

- file browser integration, means overlay icons and context menu, is not included in the AppImage
-> install the file browser extension packages manually as system packages, e.g. ```owncloud-client-nautilus``` (from linux repos at https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/)
- autostart doesn't work
- no automatic update, new version is suggested for manual update

up to here for 2.10.1

----------------------------------------------------
__For 3.0.0 release__

- runs on CentOS 7
- autostart (start on Login) works
- automatic update enabled
- knows issues for some platforms, see https://github.com/owncloud/client/issues/9631

**Comment by michaelstingl** [comment]
Better also add instructions for "Removal" to https://doc.owncloud.com/desktop/next/removing.html

**Comment by gabi18** [comment]
Tested scenarios:
- AppImageLauncher
   appimagelauncher_2.2.0-gha84.cbe7f29+bionic_amd64.deb (pre release) on Ubuntu 21.10

  ![applauncher](https://user-images.githubusercontent.com/75983861/153550848-e3875244-9650-4ff9-9086-c7e9c97d6a47.png)

**Comment by gabi18** [comment]
File browser integration with packages available from previous client version on Ubuntu 21.10 works:
- install version 2.9.2 of owncloud-client + owncloud-client-nautilus, owncloud-client-overlays-icons
- install ownCloud-2.10.0.6519.AppImage
- start AppImage, 'Open folder'
Result: overlay icons and sub menu are shown

**Comment by gabi18** [comment]
The dependency of the file browser-extensions (nemo/nautilus/caja) to the owncloud-client package is removed from Ubuntu and Debian repos (the client is suggested now).

- install owncloud-client-nautilus_2.10.1~daily20220216+oc-6800_all.deb from https://download.owncloud.com/desktop/ownCloud/daily/2.10/linux
- install ownCloud-2.10.0.6519.AppImage

Result:  owncloud-client-overlays-icons_2.10.1~daily20220216+oc-6800_all.deb gets installed, owncloud-client NOT installed, 
overlay icons and sub menu are shown

For openSUSE a requires to the client package is still there:
https://download.owncloud.com/desktop/ownCloud/daily/2.10/linux/openSUSE_Leap_15.3/repodata/xxx-primary.xml.gz 
```
<package type="rpm">
  <name>owncloud-client-nautilus</name>
  ...
   <rpm:requires>
      <rpm:entry name="owncloud-client-overlays-icons"/>
      <rpm:entry name="owncloud-client(x86-64)" flags="EQ" epoch="0" ver="2.10.1~daily20220216" rel="6800"/>
      <rpm:entry name="python3-nautilus"/>
    </rpm:requires>
```
@fmoc could you please have a look

**Comment by gabi18** [comment]
The dependencies on 'rpm' repos are fixed, tested dolphin extensions on openSUSE 15.3:

- install ownCloud-2.10.0.6519.AppImage
- install owncloud-client-dolphin

Result: owncloud-client not installed, file browser overlay and sub menu are shown

**Comment by gabi18** [comment]
ownCloud-2.11.0-daily20220301.6912.AppImage runs on CentOS 7

**Comment by jnweiger** [comment]
Documentation currently only mentions appimage in one place:
* https://doc.owncloud.com/desktop/next/installing.html#installation-on-linux

The initial comment has more details and this is not limited to install.
We probably need a new chapter for the appimage?

**Comment by gabi18** [comment]
Known issue for Ubuntu 22.04 on 2.10.1
https://docs.appimage.org/user-guide/troubleshooting/fuse.html

**Comment by jnweiger** [comment]
the issue with Ubuntu 22.04 is:
* Ubuntu ships (and installs per default) Fuse 3
* appimage currently still requires Fuse 2
* With Ubuntu 22.04 it is required to run `apt install libfuse2` to get old and new fuse libraries installed in parallel.

**Comment by mmattel** [comment]
> Ubuntu ships (and installs per default) Fuse 3 ... appimage currently still requires Fuse 2

Means we have to check the current version of fuse upfront via command:

```
fusermount -V
fusermount version: 2.9.9

```

And advise to install the correct version in case you are running v3.

**Comment by mmattel** [comment]
uhhh, see: https://github.com/AppImage/AppImageKit/wiki/FUSE

**AppImages require FUSE version 2 to run**
but
**on Ubuntu (>= 22.04): Warning: Do not install the fuse package as of 22.04 or you may break your system**

also see: https://askubuntu.com/questions/1409496/how-to-install-safely-install-fuse-on-ubuntu-22-04

:scream:

**Comment by jnweiger** [comment]
Background info:
* Ubuntu 22.04 runs its kernel with `fuse3` -- that works together with both `libfuse3` (default) and `libfuse2` (for appimage)
* An attempt to install the package `fuse` removes `fuse3` from the kernel -- unfortunately without warning. That is what breaks the system.

Doku should just not discuss the package `fuse` at all. Only speak about `libfuse2` -- even if people try to install libfuse2 on other ubuntu's -- that is also harmless (already installed). :sun_with_face:

**Comment by mmattel** [comment]
Just working on the documentation, questions raised from above:

* Note: to see systray client icons on Debian 11 `apt install gnome-shell-extension-appindicator` and enable `Ubuntu appindicators` in `Tweaks/Extensions`
**Q1**: Means D11 as mentioned but also U22.04 ?
**Q2**: Guess that this is for the GNOME desktop only. What about other desktop environments?

* start on command line with '-s' option: the client settings window is shown
**Q3**: Why, isn't it enough without the option. What is the option good for and what happens if the option is not used?

**Comment by michaelstingl** [comment]
@fmoc can you help with @mmattel 's questions? ⬆️

**Comment by mmattel** [comment]
@fmoc had a call with me today. The questions have been answered, to much writing here.
