### ISSUE TITLE
Continuous-Integration / Drone 

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-client-desktop#23]
This repo needs a CI same as in docs.

@phil-davis Help wanted and needed

@EParzefall FYI

Note 1: that atm there is no starlark file present as we have in docs. This must be created from scratch. The existing Makefile is for historical reasons only, comes from the client repo and will be removed when we have a working starlark file.

Note 2: the basic definition files of this repo should be the same as in docs, adopted to desktop but may need additional adjustments when setting up CI or a starlark file.

**Comment by xoxys** [comment]
Addressed by: https://github.com/owncloud/docs-client-desktop/pull/39 https://github.com/owncloud/docs-client-desktop/pull/40 https://github.com/owncloud/docs-client-desktop/pull/38

**Comment by xoxys** [comment]
@mmattel I guess we can close it now?

**Comment by mmattel** [comment]
yes 😄 
thanks for your great support!
