### ISSUE TITLE
Document "Force Sync Now" Button

### ISSUE THREAD

**Issue by JRundfeldt** [owncloud/docs-client-desktop#230]
The Documentation does not describe the behaviour (or even the existence) of the Button "Force Sync Now"/"Synchronisation jetzt erzwingen" 

![image](https://user-images.githubusercontent.com/95415117/162162291-b2028917-5d54-4748-b68d-2f6ff6b5082a.png)
![image](https://user-images.githubusercontent.com/95415117/162162518-90b4514b-10f1-4494-b13e-7ddbd5096bba.png)

The Documentation that needs to be created, needs to anwer these questions:

- What is the use case for this button (When should the user press it?)
- What is the expected behaviour of this button?
- What is the expected behaviour after a (resolved) conflict?

**Comment by dragotin** [comment]
AFAIR this function just schedules a sync of the folder ASAP. It was built for the case that the user knows that there was a local change on the disk that the change detection system did not pick for whatever reason. In practice that does not happen.

The functionality does not have any special meaning in regards of conflicts.

**Comment by TheOneRing** [comment]
It also triggers a complete local discovery and clears some retry block errors.
So nothing a user should press all 5 minutes.

Rename to "Schedule full sync now"? Sounds less violent.

**Comment by dragotin** [comment]
Or just "Sync now"? I guess the user expects that it is "full" anyway bc it does not understand the difference between full and not full sync...

**Comment by TheOneRing** [comment]
yep
