### ISSUE TITLE
Update AppImage related documentation before 2.11 release

### ISSUE THREAD

**Issue by fmoc** [owncloud/docs-client-desktop#250]
Some of the docs will become outdated with the upcoming 2.11 release and need to be changed:

- we now build the AppImage on CentOS 7, thus there is no compatibility problem with common older distributions any more

While reading through the docs, I noticed another bug in the docs:

```sh
sudo chmod +x ownCloud-2.10.1.7187.AppImage
```

The `sudo` bit is *not* required. AppImages generally do not require root access for regular use.

**Comment by mmattel** [comment]
> The sudo bit is not required. AppImages generally do not require root access for regular use.

This is correct, but the chmod command is 😄
