### ISSUE TITLE
Inconsistent behavior when there is a sync issue

### ISSUE THREAD

**Issue by enbrnz** [owncloud/docs-client-desktop#288]
I'm referring to the following issue:
https://github.com/owncloud/enterprise/issues/5426

Specifically the following comment sheds some light into the dark:
https://github.com/owncloud/enterprise/issues/5426#issuecomment-1308694173

I think this should be documented somewhere, however I am not sure where.
Perhaps on ["Using the Desktop App"](https://doc.owncloud.com/desktop/next/navigating.html) or alternatively in the appendices section.

We should just add a couple sentences along the lines of this (feel free to improve them):

> ### Known issues
> If the client is showing a sync error, it is obligatory to make sure to resolve them immediately.
> The error handling of such an issue is different between files and folders which can easily lead to a user inadvertently deleting files.

The customer originally reporting the issue is describing such an error loss scenario in detail in the following comment:
https://github.com/owncloud/enterprise/issues/5426#issuecomment-1306829300

**Comment by jnweiger** [comment]
@enbrnz how can this lead to deleted files?
I tried to reproduce, but the only problem I can see is that folders dont get deleted as expected, while there is an unresolved conflict pending. All actions with adding, deleting, renaming files work fine, as far as I can see.
Results see https://github.com/owncloud/enterprise/issues/5426#issuecomment-1348929283

**Comment by enbrnz** [comment]
This is what the customer wrote:

> I have also noticed that once the error is resolved and the folder delete is synchronised, any files that were created in that folder by another client or the web UI before the error is resolved are also deleted.

**Comment by mmattel** [comment]
Closing, fixed in 4.0, and for branding customer in 4.1, see the referenced issue
