### ISSUE TITLE
`owncloudcmd` documentation incorrect.

### ISSUE THREAD

**Issue by pauljherring** [owncloud/docs-client-desktop#314]
Fron: https://doc.owncloud.com/desktop/next/advanced_usage/command_line_client.html

>-h | Sync hidden files,do not ignore them.
>-- | --

`-h` is actually `Displays help on commandline options.`

Meanwhile there doesn't appear to be an option to sync hidden files using commandline options:

```
$ owncloudcmd -h
gui.platform: adding plugin directory "/opt/ownCloud/ownCloud/bin/../lib/x86_64-linux-gnu/plugins"
Usage: owncloudcmd [options] source_dir server_url remote_folder
owncloudcmd version 3.0.0.9215- - command line client tool

Options:
  -s, --silten                      Don't be so verbose.
  --httpproxy <http://server:port>  Specify a http proxy to use.
  --trust                           Trust the SSL certification
  --exclude <file>                  Path to an exclude list [file]
  --unsyncedfolders <file>          File containing the list of unsynced remote
                                    folders (selective sync)
  --server <url>                    Use [url] as the location of the server.
                                    OCIS only (server location and spaces url
                                    can differ)
  -u, --user <name>                 Use [name] as the login name
  -p, --password <password>         Use [pass] as password
  -n                                Use netrc (5) for login
  --non-interactive                 Do not block execution with interaction
  --max-sync-retries <n>            Retries maximum n times (default to 3)
  --uplimit <n>                     Limit the upload speed of files to n KB/s
  --downlimit <n>                   Limit the download speed of files to n KB/s
  --logdebug                        More verbose logging
  -h, --help                        Displays help on commandline options.
  --help-all                        Displays help including Qt specific
                                    options.
  -v, --version                     Displays version information.

Arguments:
  source_dir                        The source dir
  server_url                        The url to the server
  remote_folder                     A remote folder
```

There's also that typo in the actual help within the program (`--silten`) which probably deserves it's own ticket.

**Comment by mmattel** [comment]
@pauljherring thanks for opening this issue 👍 
I have created a fix for the table and filed an issue in the client repo regarding the typo.

Feel free to add more issues if other stuff catches your eyes 😃

**Comment by mmattel** [comment]
>  just the fact that is there (or at probably was) a method of syncing hidden files

Can you pls file an issue in the client repo, see the issue referenced above. The documentation side cant do much about command line options/arguments...

**Comment by michaelstingl** [comment]
@fmoc FYI

**Comment by pauljherring** [comment]
To close the circle on this, there'll be an additional option (`--sync-hidden-files`) to perform this functionality in `3.1`:

- https://github.com/owncloud/client/issues/10390#issuecomment-1382354212

I'm not sure if a new ticket would/will be required to update the documentation when it lands?
