### ISSUE TITLE
Add documentation that Windows VFS requires files ownership

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/docs-client-desktop#347]
When using Windows Virtual files, the user must own those,  on a filesystem level.

See https://github.com/owncloud/client/issues/10382

**Comment by mmattel** [comment]
Reading the referenced issue I cant get any info that can be molded into text. A standard user has no clue about writeable DAC and the only thing I found on the web was the `icacls /?` command respectively a [page on microsoft](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/icacls) about that command. To proceed, I definitely need much more details.

**Comment by TheOneRing** [comment]
A standard user will be owner of their files besides for share family pcs.

In order to see the file owner go to:
Properties -> Security -> Advanced 
![image](https://user-images.githubusercontent.com/200626/221832008-993a1980-d753-4636-b216-83693f538b57.png)

**Comment by TheOneRing** [comment]
The default case should be that you own your files, we probably just need to document this scenario in the trouble shooting section.
