### ISSUE TITLE
[GUI squish test] Browser installation command missing for ocis setup

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/docs-client-desktop#355]
In this section https://doc.owncloud.com/desktop/3.1/appendices/guitest.html#extra-steps-for-infinite-scale,
browser installation command missing 
``` 
npx playwright install chromium
```

**Comment by mmattel** [comment]
@saw-jan mind to create a PR, you have last time changed the gui test page, see https://github.com/owncloud/docs-client-desktop/pull/280

@Salipa-Gurung of course you can create a PR too 😄 

In any case, pls create the PR in master.

**Comment by saw-jan** [comment]
Yeah :smile: 
Either I or she will create the PR for this.
