### ISSUE TITLE
Since 2.8 the client should automatically print to the windows terminal, no workaround needed

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/docs-client-desktop#37]
Since 2.8 we atache to the terminal if possible.
That way we should see the log without the need for the workaround described in: https://github.com/owncloud/docs-client-desktop/blame/1c76993f8e48dbf495a202f0d2a6638d2f149d99/modules/ROOT/pages/appendices/troubleshooting.adoc#L112

Not using the workaround should also fix some encoding issues of the log file which can occur when using the workaround.

**Comment by jnweiger** [comment]
The described workaround is
`'C:\Program Files\ownCloud\owncloud.exe' --logfile - --logflush | Write-Host`

Which parts of that command are still needed? Probably `--logfile -` is still neeed to see the log. correct?

**Comment by mmattel** [comment]
@TheOneRing can you clarify if `Write-Host` ist still needed or what else hast changed?
I can do the fix rather quickly with that info provided.

Note: text to be changed located at: https://doc.owncloud.com/desktop/appendices/troubleshooting.html#logging-in-the-console

**Comment by TheOneRing** [comment]
` | Write-Host ` was the workaround `--logfile - --logflush ` is the same on all platforms and tells the client to print to stdout (`-`)

**Comment by mmattel** [comment]
Closing via #472 
References: #112
