### ISSUE TITLE
Troubleshooting logs mentions non exisiting argument logexpire 

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/docs-client-desktop#390]
https://doc.owncloud.com/desktop/latest/appendices/troubleshooting.html#saving-files-directly

Not sure when it was removed, but its long gone.

**Comment by michaelstingl** [comment]
@TheOneRing is there a CLI parameter or environment variable that can control the number of logfiles to keep?

![CleanShot 2023-03-01 at 10 38 28@2x](https://user-images.githubusercontent.com/214010/222101723-1e20bde6-8178-4556-97c7-2839ef8b3340.png)

**Comment by michaelstingl** [comment]
@TheOneRing needs clarification?
> Note that using any logging command line options will override the settings.

**Comment by mmattel** [comment]
Post a discussion with @TheOneRing, there is no correspondent envvar for the UI `Log files to keep`.
