### ISSUE TITLE
Reconnect button

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs-client-desktop#407]

**Comment by mmattel** [comment]
@michaelstingl can you provide more information...?

**Comment by HanaGemela** [comment]
When client gets disconnected, the Reconnect button becomes available. When user is signed out, they have to use Log in button

**Comment by mmattel** [comment]
What are reasons for a disconnction?

**Comment by michaelstingl** [comment]
> What are reasons for a disconnction?

🤷

**Comment by HanaGemela** [comment]
E.g. turned off wifi
