### ISSUE TITLE
Sharing now opens web ui

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/docs-client-desktop#411]
https://doc.owncloud.com/desktop/next/navigating.html#sharing-from-your-desktop

When connected to ocis, there is no share dialog anymore. Web UI gets opened instead

<img width="1073" alt="Screenshot 2023-05-11 at 10 26 53" src="https://github.com/owncloud/docs-client-desktop/assets/49001702/01f84304-628c-49ee-9c48-f7cbedb4cdd1">

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/docs-client-desktop/issues/322
