### ISSUE TITLE
Install gnome-extensions-app step missing in docs 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/docs-client-desktop#512]
https://doc.owncloud.com/desktop/next/installing.html#installation-on-linux

Steps to get the system tray on Fedora:

1. Install gnome-shell-extension-appindicator: `sudo dnf install gnome-shell-extension-appindicator`
2. Install gnome-extensions-app: `sudo dnf install gnome-extensions-app`
3. Restart 
4. Open Extensions app
5. Enable AppIndicator extension

The second step is missing in docs

**Comment by michaelstingl** [comment]
Additionally:
- https://github.com/owncloud/enterprise/issues/6023#issuecomment-1731332687
