### ISSUE TITLE
Documentation about Syncing of "problematic" filenames 

### ISSUE THREAD

**Issue by dragotin** [owncloud/docs-client-desktop#52]
We need to document the systems behavior with filenames containing forbidden chars, spaces at the end, four byte emoticons and stuff.

@carlaschroder this is just a reminder so far, I am happy to come up with a first draft if you point me where that should be added in the doc.

**Comment by mmattel** [comment]
We can take the input of
https://github.com/owncloud/core/issues/29759 [Feature Request] Check if file names restrictions apply for a given mount (filesystem)
to document the various limitations

**Comment by mmattel** [comment]
Closed via #87
