### ISSUE TITLE
Do not use rpm tool for installing rpm linux packages 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/docs-client-desktop#524]
`rpm -i `is not a suitable tool for installing the rpm linux packages, it doesn't uninstall the package's predecessor and then the new and old packages collide with each other

Use `dnf install` instead

**Comment by mmattel** [comment]
@HanaGemela can you point me to a location where this is used?
I did a `grep -rn "rpm"` and got no results....?

**Comment by HanaGemela** [comment]
Then all good if we don't mention rpm all
