### ISSUE TITLE
NTFS is mandatory with Windows, FAT (or derivates) are not working properly

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-client-desktop#90]
Referencing: https://github.com/owncloud/client/issues/8913 (Moving files causes delete and re-upload with second Folder Sync Connection)

Document that you have to use NTFS and not any FAT variant on Windows, which is especially true for external connected drives (like via USB)

Background:
> In the FAT file system, the file ID is generated from the first cluster of the containing directory and the byte offset within the directory of the entry for the file. Some defragmentation products change this byte offset. (Windows in-box defragmentation does not.) Thus, a FAT file ID can change over time. Renaming a file in the FAT file system can also change the file ID, but only if the new file name is longer than the old one.
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/ns-fileapi-by_handle_file_information

Backport to 2.7 and 2.8 necessary

@TheOneRing @Darkexy fyi

**Comment by TheOneRing** [comment]
I'd say recommended as FAT offers limitations
